[aws]
symbol = " "

[java]
symbol = " "

[scala]
symbol = " "

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[time]
disabled = false
